CREATE TABLE IF NOT EXISTS DO_USER
(
    ID            BIGINT           NOT NULL AUTO_INCREMENT,
    EMAIL_ADDRESS VARCHAR(128)     NOT NULL,
    FIRSTNAME     VARCHAR(32),
    LASTNAME      VARCHAR(32),
    AGE           INT(3),
    ACTIVE        BOOLEAN,
    COUNTRY       VARCHAR(255),
    CITY          VARCHAR(255),
    STREET_NAME   VARCHAR(255),
    STREET_NO     VARCHAR(255),
    MANAGER_ID    BIGINT,
    VERSION       BIGINT DEFAULT 0 NOT NULL,
    DELETED       INT(1) DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY (EMAIL_ADDRESS)
);

CREATE TABLE IF NOT EXISTS DO_ROLE
(
    ID   BIGINT      NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(64) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY (NAME)
);

CREATE TABLE IF NOT EXISTS DO_USER_ROLE
(
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID)
);