CREATE TABLE "SITE_CONTENT" (
  "ID" SERIAL NOT NULL,
  "NAME" varchar(50) DEFAULT NULL,
  "SITE_FUNCTION_ID" BIGINT NOT NULL,
  CONSTRAINT function_fk FOREIGN KEY("SITE_FUNCTION_ID") REFERENCES "SITE_FUNCTION"("ID"),
  PRIMARY KEY ("ID"),
  CONSTRAINT sites_content_unique UNIQUE ("NAME")
);
