CREATE TABLE "SITE_FUNCTION" (
  "ID" SERIAL NOT NULL,
  "NAME" varchar(50) DEFAULT NULL,
  "SITE_SERVICE_ID" BIGINT NOT NULL,
  CONSTRAINT service_fk FOREIGN KEY("SITE_SERVICE_ID") REFERENCES "SITE_SERVICE"("ID"),
  PRIMARY KEY ("ID"),
  CONSTRAINT sites_function_unique UNIQUE ("NAME")
);
