name: Build
on: [ push ]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: [ 8, 11, 17 ]
        name: 'Build on Java ${{ matrix.java }}'
        steps:
            -   uses: actions/checkout@v3
            -   name: 'Set up JDK ${{ matrix.java }}'
                uses: actions/setup-java@v3
                with:
                    java-version: '${{ matrix.java }}'
                    distribution: 'adopt'
            -   name: Build with Gradle
                run: ./mvnw clean package -U
